dependencies:
  flutter:
    sdk: flutter
  
  # Hanya Just Audio yang diperlukan untuk memutar asset
  just_audio: ^0.9.36 # Pastikan versi terbaru
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
  
  # DAFTARKAN FOLDER ASSETS DI SINI
  assets:
    - assets/audio/
